name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pyhton Test
      run:
        python -m agile_processes_python.tests.test
